config/routes.rb
Website::Application.routes.draw do
  root :to => 'static_page#index'
  
  resources :pr, :controller => "PressReleases", :only => [:index, :show]
  
  match '/:slug' => 'categories#show', :as => :category
  match '/:category/:slug' => 'products#show', :as => :category_product
  match '/:category/:product/:slug' => 'detail_pages#show', :as => :category_product_detail_page
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :destroy
  
  attr_accessible :tagline, :title, :slug
  
  validates :title, :presence => true
  validates :slug, :presence => true, :uniqueness => true
end

app/models/detail_page.rb
class DetailPage < ActiveRecord::Base
  belongs_to :product
  
  attr_accessible :content, :slug, :subtitle, :title
end

app/models/press_release.rb
class PressRelease < ActiveRecord::Base
  belongs_to :product
  
  attr_accessible :content, :headline, :subhead
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :detail_pages, :dependent => :destroy
  has_many :press_releases
  
  attr_accessible :content, :excerpt, :slug, :tagline, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :categories
  
  def categories
    Category.all()
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by_slug(params[:slug])
    render :file => 'public/404.html', :status => 404 and return if @category.nil?
  end
end

app/controllers/detail_pages_controller.rb
class DetailPagesController < ApplicationController
  def show
    category = Category.where(:slug => params[:category]).first
    render :file => "public/404.html", :status => 404 and return if category.nil?
    
    @product = Product.where(:slug => params[:product], :category_id => category.id).first
    render :file => "public/404.html", :status => 404 and return if @product.nil?
    
    @detail_page = DetailPage.where(:slug => params[:slug], :product_id => @product.id).first
    render :file => "public/404.html", :status => 404 and return if @detail_page.nil?
  end
end

app/controllers/press_releases_controller.rb
class PressReleasesController < ApplicationController
  def index
    @releases = PressRelease.find(:all,
                                  :order => 'press_releases.created_at desc',
                                  :limit => 5)
  end

  def show
    @pr = PressRelease.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    category = Category.where('slug = :slug', :slug => params[:category]).limit(1)[0]
    render :file => "public/404.html", :status => 404 and return if category.nil?
    
    @product = Product.where('slug = :slug AND category_id = :category_id', :slug => params[:slug], :category_id => category.id).limit(1)[0]
    render :file => "public/404.html", :status => 404 and return if @product.nil?
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdownify(text)
    BlueCloth.new(text).to_html.html_safe
  end
  
  def make_sidebar_for(product)
    sidebar = '<ul class="nav nav-list">'
    sidebar += "#{active_link_to product.title, category_product_path(product.category.slug, product.slug), :active => :exclusive, :wrap_tag => :li}"
    product.detail_pages.each {|page| sidebar += "#{active_link_to page.title, category_product_detail_page_path(product.category.slug, product.slug, page.slug), :wrap_tag => :li}"}
    sidebar += "</ul>"
    sidebar.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/detail_pages_helper.rb
module DetailPagesHelper
end

app/helpers/press_releases_helper.rb
module PressReleasesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/categories/show.html.erb
<% provide :title, @category.title %>

<h1 class="page-header">
  <%= @category.title %>
  <% unless @category.tagline.nil? %><small><%= @category.tagline %></small><% end %>
</h1>

<% @category.products.each { |product| %>
  <%= "<img src=\"#{product.image_url}\" alt=\"\" style=\"float:left;\">".html_safe unless product.image_url.nil? %>
  <h2><%= link_to product.title, category_product_path(@category.slug, product.slug) %></h2>
  <em><%= product.excerpt %></em>
  <%= "<div style=\"clear:both;\"></div>".html_safe unless product.image_url.nil? %>
<% } %>

app/views/detail_pages/show.html.erb
<% provide :title, @detail_page.title %>
<% provide :sidebar, make_sidebar_for(@product) %>

<h1 class="page-header"><%= @detail_page.title %><% unless @detail_page.subtitle.nil? %> <small><%= @detail_page.subtitle %></small><% end %></h1>

<%= markdownify @detail_page.content %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title><%= content_for?(:title) ? yield(:title) : "Wilcox Technologies" %></title>
    <%= csrf_meta_tags %>
    <meta name="google-site-verification" content="KF4Ev5lMFtiZHdhCUnh5kczs9HF_KXT8lgCjKbeXXkk">
    <% if content_for?(:meta_desc) %><meta name="description" content="<%= yield(:meta_desc) %>"><% end %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if lt IE 7]>
      <link href="/ie6.css" rel="stylesheet" name="Please upgrade your browser.">
    <![endif]-->
    <style type="text/css">
    @import("/ie6.css");
    </style>

    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.0.4/css/bootstrap-combined.min.css"
      rel="stylesheet" name="Bootstrap, from Twitter">
    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="/images/favicon.ico" rel="shortcut icon">
    <link href="/images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="/images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="/images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28082705-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

      function recordOutboundLink(link, category, action) {
        try {
          _gaq.push(['_trackEvent', category ,  action ]);
          setTimeout('document.location = "' + link.href + '"', 100)
        }catch(err){}
      }
    
    </script>
    <!-- Javascripts
    ================================================== -->
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="http://current.bootstrapcdn.com/bootstrap-v204/js/bootstrap.min.js" type="text/javascript"></script>

  </head>
  <body <%= content_for?(:body_tag) ? "id=#{content_for :body_tag}" : "" %>>
    <nav><div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">&nbsp;</a>
            <ul class="nav">
              <%= active_link_to 'Home', '/', :wrap_tag => :li %>
              <% categories.each do |cat| %>
                <%= active_link_to cat.title, category_path(cat.slug), :wrap_tag => :li %>
              <% end %>
              <!-- <li><a href="http://blogs.wilcox-tech.com/">Blogs</a></li> -->
              <!-- <li><a href="http://people.wilcox-tech.com/">People</a></li> -->
            </ul>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <li><a href="https://twitter.com/Wilcox_Tech"><img src="/images/twitter.png" alt="Twitter" title="Follow us on Twitter"/></a></li>
              <li><a href="https://www.facebook.com/WilcoxTech"><img src="/images/fbicon.png" alt="Facebook" title="Like us on Facebook"/></a></li>
              <li><a href="/about/contact">Contact</a></li>
              <li><a href="http://oss.wilcox-tech.com/">Open Source</a></li>
              <%= active_link_to 'Press', '/pr', :wrap_tag => :li %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div></nav>

    <div class="container">
      <div class="content">
        <div class="row">
          <% if content_for?(:sidebar) %>
            <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <%= yield :sidebar %>
            </div><!--/span-->
          <% else %>
            <div class="span12">
              <%= yield %>
            </div>
          <% end %>
        </div><!--/row-->
      </div><!--/content-->
      <div class="clearfix_ie_only">&nbsp;</div>
      <footer>
        <hr/>
        <p>&copy; <%= Time.now.year %> Wilcox Technologies, LLC</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/press_releases/index.html.erb
<% provide :title, 'Wilcox Technologies Press Information' %>
<% provide :meta_desc, 'Press releases, images, and information about Wilcox Technologies, maker of apps for Mac and iPhone.' %>

<h1 class="page-header">Press Information <small>Press releases, images, and information.</small></h1>

<div class="row">
  <div class="span3">
    <div style="text-align:center;">
      <h3>Press Inquiries</h3>
      <h4>+1 (415) 484-WT-PR (9877)</h4>
    </div>
    
    <!-- Hard line breaks make Corgi sad, but it is necessary to look right. -->
    <br/>
    
    <p>Not a member of the press?  See <a href="/about/contact" title="How to Contact Us">how to contact us</a>.</p>
    
    <address><b>Wilcox Technoloiges LLC</b><br/>
    719 Sunny Pine Way Suite H1<br/>
    Greenacres, Florida 33415<br/>
    United States</address>
  </div>
  <div class="span6">
    <h2>Press Releases</h2>
    <dl class="dl-horizontal">
    <% @releases.each {|pr| %>
      <dt><%= pr.updated_at.strftime('%F') %></dt>
      <dd><h4><a href="/pr/<%= pr.id %>"><%= pr.headline %></a></h4></dd>
    <% } %>
    </dl>
  </div>
  <div class="span3">
    <div class="well" style="padding: 8px 0;">
      <ul class="nav nav-list">
        <li class="nav-header">Resources for the Press</li>
        <!-- <li><a href="#"><i class="icon-picture"></i> Product Images and Info</a></li> -->
        <!-- we should enable this link when we have > 10 PRs
        <li><a href="#"><i class="icon-book"></i> Press Release Archive</a></li>
        -->
        <li><a href="/about/team"><i class="icon-user"></i> Team Biographies</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/press_releases/show.html.erb
<% provide :title, "#{@pr.headline}" %>
<% provide :meta_desc, @pr.subhead %>

<% provide :sidebar, make_sidebar_for(@pr.product) unless @pr.product.nil? %>

<h1 class="page-header">Press Information <small>Press releases, images, and information.</small></h1>

<div class="pr-content">
  <h1 class="pr-headline"><%= @pr.headline %></h1>
  <h3 class="pr-subhead"><%= @pr.subhead %></h2>
  
  <%= markdownify @pr.content %>
</div>

app/views/products/show.html.erb
<% provide :title, "#{@product.title} by Wilcox Technologies" %>
<% provide :meta_desc, @product.excerpt %>

<% provide :sidebar, make_sidebar_for(@product) if @product.detail_pages.any? %>

<div class="page-header">
  <h1><%= @product.title %><% unless @product.tagline.nil? %> <small><%= @product.tagline %></small><% end %></h1>
</div>

<%= markdownify(@product.content) %>

app/views/static_page/index.html.erb
<% provide :title, 'Welcome to Wilcox Technologies: Apps for iPhone and Mac OS X' %>
<% provide :meta_desc, 'Wilcox Technologies makes apps for iPhone and Mac OS X that are powerful and easy to use.  Makers of Auctions for iPhone and Findalike.' %>
<% provide :body_tag, 'home' %>

<div class="hero-unit">
  <div class="row">
    <div class="span6">
      <div class="grey-transparent">
        <h1><small>Introducing</small> Auctions.</h1>
        <p>Sell anything on eBay and Etsy.  All from your iPhone.</p>
      </div>
      <p><a href="/lifestyle/auctions"><button class="btn-primary btn-large btn-info">Learn More &raquo;</button></a></p>
    </div>
  </div>
</div>

<div class="clearfix_ie_only">&nbsp;</div>

<div id="main_content">
  <div class="page-header">
    <h1>Welcome to Wilcox Technologies.  <small>Software and apps for iPhone and Mac OS X.</small></h1>
    <p>
      <strong>We strive to make your life easier with high-quality software that is both powerful and easy to use.</strong>
      We know your time is valuable &ndash; that's why we spend our time making fast and reliable software.
      You'll love to use our software as much as we loved making it for you.
    </p>
  </div>
  
  <div class="row">
    <div class="span6">
      <h3><a href="/games">Games</a></h3>
      <p>Unwind with your mobile and one of our fun games, like <a href="/games/findalike">Findalike</a>.</p>
    </div>
    
    <!--<div class="span4">
      <h3>Health</h3>
      <p>maybe we shouldn't have this one until SugarDaddy is out</p>
    </div>-->
    
    <div class="span6">
      <h3><a href="/lifestyle">Lifestyle</a></h3>
      <p></p>
    </div>
  </div>
  
  <div class="row">
    <div class="span4">
      <h3>Open Source</h3>
      <p>
        We believe strongly in the power of open-source and invite you to
        <a href="http://oss.wilcox-tech.com/">learn more about Open Source at
        Wilcox Technologies.</a>
      </p>
    </div>
    
    <div class="span4">
      <h3>Support</h3>
      <p>Have a question about how to use our software?  Have a comment about
         how we can make our software work better for you?  Now you can ask
         just about anything on <a href="http://support.wilcox-tech.com/">our new support site</a>.</p>
    </div>
    
    <div class="span4">
      <h3>Connect With Us</h3>
      <p>
        Connect with us on <a href="https://www.facebook.com/WilcoxTech">Facebook</a> or
        <a href="https://twitter.com/Wilcox_Tech">Twitter</a> for the latest updates about
        Wilcox Technologies software: tips, tricks, and new releases you'll love.
      </p>
    </div>
  </div>